FROM alpine:3.21

ARG TARGETPLATFORM

RUN apk add --no-cache ca-certificates tzdata

COPY $TARGETPLATFORM/omnipus /usr/local/bin/omnipus
COPY $TARGETPLATFORM/omnipus-launcher /usr/local/bin/omnipus-launcher
COPY $TARGETPLATFORM/omnipus-launcher-tui /usr/local/bin/omnipus-launcher-tui

ENTRYPOINT ["omnipus-launcher"]
CMD ["-public", "-no-browser"]
